spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factory
    username: postgres
    password: terrrr
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # создает таблицы если не существует, дополняет существующие таблицы колонками
      #ddl-auto: create - удаляет перед созданием существующие таблицы, создает новые
      #ddl-auto: create-drop - тоже что и create + при окончании работы приложения удаляет существующие таблицы
      #ddl-auto: none - не будет создавать, удалять, изменять сущности(таблицы, сиквенсы, констрейнты) в бд
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE